import nbformat
from nbformat.v4 import new_notebook, new_code_cell, new_markdown_cell

nb = new_notebook()
nb.cells = [
    new_markdown_cell('# Backtesting & Final Analysis\n## RAPO-AS-RL: Three-way Strategy Comparison'),
    new_code_cell('import warnings\nwarnings.filterwarnings("ignore")\n%cd C:/Users/zihan/capstone\nimport json, logging, pickle\nfrom datetime import datetime\nfrom pathlib import Path\nimport matplotlib.pyplot as plt\nimport numpy as np\nimport pandas as pd\nimport seaborn as sns\nfrom scipy import stats\nsns.set_style("whitegrid")\nplt.rcParams["figure.figsize"] = (14, 6)\nplt.rcParams["font.size"] = 11\nlogging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")\nlog = logging.getLogger(__name__)\nROOT = Path("C:/Users/zihan/capstone")\nDATA_DIR = ROOT / "data" / "processed"\nMODEL_DIR = ROOT / "models"\nBACKTEST_DIR = MODEL_DIR / "backtest"\nBACKTEST_DIR.mkdir(parents=True, exist_ok=True)'),
    new_markdown_cell('---'),
    new_markdown_cell('## 1. Data Setup'),
    new_code_cell('price_df = pd.read_parquet(DATA_DIR / "price_features.parquet")\ntrades_df = pd.read_parquet(DATA_DIR / "trades_processed.parquet")\nif "timestamp" in price_df.columns:\n    price_df = price_df.set_index("timestamp")\n    price_df.index = pd.to_datetime(price_df.index)\nlog.info(f"Price data shape: {price_df.shape}, range: {price_df.index.min()} to {price_df.index.max()}")\nimport joblib\nhmm_model = joblib.load(MODEL_DIR / "hmm" / "hmm_model.pkl")\nregime_labels = pd.read_csv(MODEL_DIR / "hmm" / "regime_labels.csv", index_col=0).iloc[:, 0]\nregime_labels.index = pd.to_datetime(regime_labels.index)\nlog.info(f"Regime labels: {regime_labels.shape}, distribution: {regime_labels.value_counts().to_dict()}")'),
    new_code_cell('as_cost_models = {}\nfor regime in ["Calm", "Volatile", "Stressed"]:\n    pkl_path = MODEL_DIR / "as_cost" / f"as_cost_{regime.lower()}.pkl"\n    if pkl_path.exists():\n        as_cost_models[regime] = joblib.load(pkl_path)\n        log.info(f"Loaded A&S cost model: {regime}")\nlgbm_forecasters = {}\nfor asset in ["BTC", "ETH"]:\n    lgbm_forecasters[asset] = {}\n    for regime in ["Calm", "Volatile", "Stressed"]:\n        pkl_path = MODEL_DIR / "lgbm" / f"lgbm_{asset.lower()}_{regime.lower()}.pkl"\n        if pkl_path.exists():\n            lgbm_forecasters[asset][regime] = joblib.load(pkl_path)\nlog.info(f"Loaded LightGBM forecasters")'),
    new_code_cell('from stable_baselines3 import PPO\nrl_policies = {}\nfor regime in ["Calm", "Volatile", "Stressed"]:\n    policy_path = MODEL_DIR / "rl" / f"ppo_{regime.lower()}.zip"\n    if policy_path.exists():\n        rl_policies[regime] = PPO.load(str(policy_path))\n        log.info(f"Loaded RL policy: {regime}")'),
    new_code_cell('data_min = price_df.index.min()\ndata_max = price_df.index.max()\nTRAIN_END = data_min + pd.Timedelta(days=20)\nVAL_END = data_min + pd.Timedelta(days=25)\ntrain_mask = price_df.index <= TRAIN_END\nval_mask = (price_df.index > TRAIN_END) & (price_df.index <= VAL_END)\ntest_mask = price_df.index > VAL_END\nprice_train = price_df[train_mask]\nprice_val = price_df[val_mask]\nprice_test = price_df[test_mask]\nregime_train = regime_labels[regime_labels.index <= TRAIN_END]\nregime_val = regime_labels[(regime_labels.index > TRAIN_END) & (regime_labels.index <= VAL_END)]\nregime_test = regime_labels[regime_labels.index > VAL_END]\nlog.info(f"Train: {len(price_train)} bars, Val: {len(price_val)} bars, Test: {len(price_test)} bars")'),
    new_markdown_cell('---'),
    new_markdown_cell('## 2. Helper Functions'),
    new_code_cell('ANN_FACTOR = 288 * 365\n\ndef get_rebalance_dates(index, frequency="Q"):\n    try:\n        periods = index.to_period(frequency)\n        return index[index.isin(periods.to_timestamp())]\n    except:\n        freq_map = {"QE": "Q", "Q": "Q"}\n        freq = freq_map.get(frequency, frequency)\n        periods = index.to_period(freq)\n        return index[index.isin(periods.to_timestamp())]\n\ndef get_current_regime(timestamp, regime_labels):\n    if timestamp in regime_labels.index:\n        return regime_labels.loc[timestamp]\n    diffs = np.abs((regime_labels.index - timestamp).total_seconds())\n    return regime_labels.iloc[diffs.argmin()]\n\ndef compute_metrics(returns, turnover):\n    ann_ret = returns.mean() * ANN_FACTOR\n    ann_vol = returns.std() * np.sqrt(ANN_FACTOR)\n    sharpe = ann_ret / ann_vol if ann_vol > 0 else 0.0\n    cumret = (1 + returns).cumprod()\n    peak = cumret.cummax()\n    max_dd = ((cumret - peak) / peak).min()\n    return {"Ann. Return": ann_ret, "Ann. Vol": ann_vol, "Sharpe": sharpe, "Max Drawdown": max_dd, "Mean Turnover": turnover.mean()}\n\ndef compute_as_cost(trade_value, price, cost_model):\n    if not cost_model or price == 0: return 0.0\n    sigma = cost_model.get("volatility", 0.0) / np.sqrt(365 * 288)\n    s = cost_model.get("spread", 0.0)\n    delta = cost_model.get("depth", 1.0)\n    gamma = cost_model.get("gamma", 1e-6)\n    q = trade_value / price\n    return sigma * np.sqrt(q / (2 * delta)) * price + (s / 2) * q + gamma * (q**2) / (2 * delta) * price'),
    new_markdown_cell('---'),
    new_markdown_cell('## 3. Strategy 1 - Flat Baseline'),
    new_code_cell('def total_return(start_ts, end_ts, weights, price_data):\n    btc_ret = (price_data.loc[end_ts, "btc_close"] - price_data.loc[start_ts, "btc_close"]) / price_data.loc[start_ts, "btc_close"]\n    eth_ret = (price_data.loc[end_ts, "eth_close"] - price_data.loc[start_ts, "eth_close"]) / price_data.loc[start_ts, "eth_close"]\n    return weights[0] * btc_ret + weights[1] * eth_ret\n\ndef run_flat_baseline(price_data, transaction_cost_bps=10):\n    rebal_dates = get_rebalance_dates(price_data.index, frequency="Q")\n    portfolio_value = pd.Series(index=price_data.index, dtype=float)\n    portfolio_value.iloc[0] = 1.0\n    current_weights = np.array([0.5, 0.5])\n    turnover_list = [0.0]\n    for i, ts in enumerate(price_data.index):\n        if i == 0: continue\n        prev_ts = price_data.index[i-1]\n        rebalance = ts in rebal_dates\n        if rebalance:\n            target_weights = np.array([0.5, 0.5])\n            delta_w = np.abs(target_weights - current_weights)\n            trade_notional = delta_w * portfolio_value.iloc[i-1]\n            total_cost = (trade_notional[0] + trade_notional[1]) * transaction_cost_bps / 10000\n            portfolio_value.iloc[i] = portfolio_value.iloc[i-1] + total_return(prev_ts, ts, current_weights, price_data) - total_cost\n            current_weights = target_weights\n            turnover_list.append(delta_w.sum())\n        else:\n            portfolio_value.iloc[i] = portfolio_value.iloc[i-1] * (1 + total_return(prev_ts, ts, current_weights, price_data))\n            turnover_list.append(0.0)\n    return portfolio_value, portfolio_value.pct_change().fillna(0), pd.Series(turnover_list, index=price_data.index)\n\nflat_equity, flat_returns, flat_turnover = run_flat_baseline(price_test)\nflat_metrics = compute_metrics(flat_returns, flat_turnover)\nlog.info(f"Flat Baseline metrics: {flat_metrics}")'),
    new_markdown_cell('---'),
    new_markdown_cell('## 4. Strategy 2 - A&S + CVaR'),
    new_code_cell('def optimize_cvar_weights(regime, cost_model, price_data, alpha=0.05):\n    btc_ret = price_data["btc_close"].pct_change().fillna(0)\n    eth_ret = price_data["eth_close"].pct_change().fillna(0)\n    returns_mat = np.column_stack([btc_ret.values, eth_ret.values])\n    best_weights = np.array([0.5, 0.5])\n    best_cvar = np.inf\n    for w_btc in np.linspace(0, 1, 21):\n        w = np.array([w_btc, 1 - w_btc])\n        port_ret = returns_mat @ w\n        var = np.percentile(port_ret, alpha * 100)\n        cvar = port_ret[port_ret <= var].mean()\n        if cvar < best_cvar:\n            best_cvar = cvar\n            best_weights = w\n    return best_weights\n\ndef run_as_cvar_strategy(price_data, regime_labels, as_cost_models, alpha=0.05):\n    rebal_dates = get_rebalance_dates(price_data.index, frequency="Q")\n    portfolio_value = pd.Series(index=price_data.index, dtype=float)\n    portfolio_value.iloc[0] = 1.0\n    current_weights = np.array([0.5, 0.5])\n    turnover_list = [0.0]\n    for i, ts in enumerate(price_data.index):\n        if i == 0: continue\n        prev_ts = price_data.index[i-1]\n        rebalance = ts in rebal_dates\n        if rebalance:\n            regime = get_current_regime(ts, regime_labels)\n            cost_model = as_cost_models.get(regime, {})\n            lookback_data = price_data.iloc[max(0, i-60):i]\n            target_weights = optimize_cvar_weights(regime, cost_model, lookback_data, alpha)\n            delta_w = np.abs(target_weights - current_weights)\n            trade_notional = delta_w * portfolio_value.iloc[i-1]\n            btc_price = price_data["btc_close"].iloc[i]\n            eth_price = price_data["eth_close"].iloc[i]\n            total_cost = compute_as_cost(trade_notional[0], btc_price, cost_model) + compute_as_cost(trade_notional[1], eth_price, cost_model)\n            portfolio_value.iloc[i] = portfolio_value.iloc[i-1] * (1 + total_return(prev_ts, ts, current_weights, price_data)) - total_cost\n            current_weights = target_weights\n            turnover_list.append(delta_w.sum())\n        else:\n            portfolio_value.iloc[i] = portfolio_value.iloc[i-1] * (1 + total_return(prev_ts, ts, current_weights, price_data))\n            turnover_list.append(0.0)\n    return portfolio_value, portfolio_value.pct_change().fillna(0), pd.Series(turnover_list, index=price_data.index)\n\nas_cvar_equity, as_cvar_returns, as_cvar_turnover = run_as_cvar_strategy(price_test, regime_test, as_cost_models)\nas_cvar_metrics = compute_metrics(as_cvar_returns, as_cvar_turnover)\nlog.info(f"A&S + CVaR metrics: {as_cvar_metrics}")'),
    new_markdown_cell('---'),
    new_markdown_cell('## 5. Strategy 3 - Full RL Agent'),
    new_code_cell('def run_rl_strategy(price_data, regime_labels, as_cost_models, rl_policies, lgbm_forecasters):\n    try:\n        from src.layer4_rl.rl_env import RegimePortfolioEnv\n        env = RegimePortfolioEnv(price_data=price_data, regime_labels=regime_labels, as_cost_models=as_cost_models, forecasters=lgbm_forecasters)\n        obs, _ = env.reset()\n        equity_vals = [1.0]\n        turnover_list = [0.0]\n        done = truncated = False\n        while not (done or truncated):\n            regime_str = get_current_regime(env.price_data.index[env.t], regime_labels)\n            policy = rl_policies.get(regime_str)\n            action = env.current_weights[:2] if policy is None else policy.predict(obs, deterministic=True)[0]\n            old_weights = env.current_weights.copy()\n            obs, reward, done, truncated, info = env.step(action)\n            turnover_list.append(np.abs(action - old_weights[:2]).sum())\n            equity_vals.append(env.portfolio_value)\n        n = len(price_data)\n        equity_vals = equity_vals[:n] + [equity_vals[-1]] * max(0, n - len(equity_vals))\n        turnover_list = turnover_list[:n] + [0.0] * max(0, n - len(turnover_list))\n        equity_curve = pd.Series(equity_vals, index=price_data.index)\n        return equity_curve, equity_curve.pct_change().fillna(0), pd.Series(turnover_list, index=price_data.index)\n    except Exception as e:\n        log.error(f"RL strategy failed: {e}")\n        return run_flat_baseline(price_data)\n\nrl_equity, rl_returns, rl_turnover = run_rl_strategy(price_test, regime_test, as_cost_models, rl_policies, lgbm_forecasters)\nrl_metrics = compute_metrics(rl_returns, rl_turnover)\nlog.info(f"RL Agent metrics: {rl_metrics}")'),
    new_markdown_cell('---'),
    new_markdown_cell('## 6. Performance Comparison'),
    new_code_cell('# Align all series\nmin_len = min(len(flat_returns), len(as_cvar_returns), len(rl_returns))\nflat_returns = flat_returns.iloc[:min_len]; as_cvar_returns = as_cvar_returns.iloc[:min_len]; rl_returns = rl_returns.iloc[:min_len]\nflat_equity = flat_equity.iloc[:min_len]; as_cvar_equity = as_cvar_equity.iloc[:min_len]; rl_equity = rl_equity.iloc[:min_len]\nflat_turnover = flat_turnover.iloc[:min_len]; as_cvar_turnover = as_cvar_turnover.iloc[:min_len]; rl_turnover = rl_turnover.iloc[:min_len]\nregime_test = regime_test.iloc[:min_len]\nflat_metrics = compute_metrics(flat_returns, flat_turnover)\nas_cvar_metrics = compute_metrics(as_cvar_returns, as_cvar_turnover)\nrl_metrics = compute_metrics(rl_returns, rl_turnover)\ncomparison = pd.DataFrame({"Flat Baseline": flat_metrics, "A&S + CVaR": as_cvar_metrics, "RL Agent": rl_metrics})\nprint("=== Performance Comparison (Test Period) ===")\nprint(comparison.round(4).to_string())'),
    new_markdown_cell('### 6.1 Equity Curves (Log Scale)'),
    new_code_cell('fig, axes = plt.subplots(2, 1, figsize=(14, 10), sharex=True)\nax1 = axes[0]\nax1.plot(flat_equity.index, flat_equity.values, label="Flat Baseline", color="gray", alpha=0.7)\nax1.plot(as_cvar_equity.index, as_cvar_equity.values, label="A&S + CVaR", color="blue")\nax1.plot(rl_equity.index, rl_equity.values, label="RL Agent", color="green")\nax1.set_yscale("log"); ax1.set_ylabel("Portfolio Value (log scale)"); ax1.legend(); ax1.grid(alpha=0.3)\nregime_map = {"Calm": 0, "Volatile": 1, "Stressed": 2}\nregime_numeric = regime_test.map(regime_map).fillna(0)\nax2 = axes[1]\nax2.fill_between(regime_test.index, 0, 1, where=(regime_numeric==0), color="green", alpha=0.2, label="Calm")\nax2.fill_between(regime_test.index, 0, 1, where=(regime_numeric==1), color="orange", alpha=0.2, label="Volatile")\nax2.fill_between(regime_test.index, 0, 1, where=(regime_numeric==2), color="red", alpha=0.2, label="Stressed")\nax2.set_ylabel("Regime"); ax2.set_yticks([]); ax2.legend(loc="upper right"); ax2.set_title("HMM Regime Over Test Period")\nplt.tight_layout()\nplt.savefig(BACKTEST_DIR / "backtest_equity_curves.png", dpi=150, bbox_inches="tight")\nplt.show()\nlog.info(f"Saved: {BACKTEST_DIR / \'backtest_equity_curves.png\'}")'),
    new_markdown_cell('---'),
    new_markdown_cell('## 7. Regime-Conditional Performance'),
    new_code_cell('def regime_conditional_metrics(returns, regime_labels):\n    results = []\n    for regime in ["Calm", "Volatile", "Stressed"]:\n        mask = regime_labels == regime\n        if mask.sum() == 0: continue\n        regime_ret = returns[mask]\n        if len(regime_ret) == 0: continue\n        ann_ret = regime_ret.mean() * ANN_FACTOR\n        ann_vol = regime_ret.std() * np.sqrt(ANN_FACTOR)\n        sharpe = ann_ret / ann_vol if ann_vol > 0 else 0.0\n        cumret = (1 + regime_ret).cumprod()\n        max_dd = ((cumret - cumret.cummax()) / cumret.cummax()).min()\n        results.append({"Regime": regime, "N": mask.sum(), "AnnRet": ann_ret, "AnnVol": ann_vol, "Sharpe": sharpe, "MaxDD": max_dd})\n    return pd.DataFrame(results).set_index("Regime")\nprint("=== Regime-Conditional Performance ===")\nfor name, rets in [("Flat", flat_returns), ("A&S+CVaR", as_cvar_returns), ("RL", rl_returns)]:\n    print(f"\\n{name}:\")\n    print(regime_conditional_metrics(rets, regime_test).round(4).to_string())'),
    new_markdown_cell('---'),
    new_markdown_cell('## 8. Statistical Validation'),
    new_code_cell('def bootstrap_sharpe_ci(returns, n_bootstrap=1000, ci=0.95):\n    sharpes = []\n    n = len(returns)\n    for _ in range(n_bootstrap):\n        idx = np.random.choice(n, size=n, replace=True)\n        boot_ret = returns.iloc[idx]\n        ann_ret = boot_ret.mean() * ANN_FACTOR\n        ann_vol = boot_ret.std() * np.sqrt(ANN_FACTOR)\n        sharpes.append(ann_ret / ann_vol if ann_vol > 0 else 0.0)\n    lower = np.percentile(sharpes, (1-ci)/2*100)\n    upper = np.percentile(sharpes, (1+ci)/2*100)\n    return np.mean(sharpes), lower, upper\n\ndef newey_west_tstat(rets1, rets2, max_lag=5):\n    n = min(len(rets1), len(rets2))\n    diff = rets1.iloc[:n].values - rets2.iloc[:n].values\n    n = len(diff)\n    gamma = [np.mean(diff[:n-k] * diff[k:]) for k in range(max_lag + 1)]\n    weights = np.array([1 - k / (max_lag + 1) for k in range(max_lag + 1)])\n    var_hac = gamma[0] + 2 * sum(weights[1:] * gamma[1:])\n    se = np.sqrt(var_hac / n)\n    t_stat = diff.mean() / se if se > 0 else 0.0\n    p_value = 2 * (1 - stats.t.cdf(abs(t_stat), df=n-1))\n    return t_stat, p_value\n\nprint("=== Bootstrap 95% CI for Sharpe Ratio ===")\nfor name, rets in [("Flat", flat_returns), ("A&S+CVaR", as_cvar_returns), ("RL", rl_returns)]:\n    m, l, u = bootstrap_sharpe_ci(rets)\n    print(f"{name}: Sharpe={m:.3f} [{l:.3f}, {u:.3f}]")\n\nprint("\\n=== Newey-West t-tests (Return Differences) ===")\nfor name, r1, r2 in [("Flat vs A&S+CVaR", flat_returns, as_cvar_returns), ("Flat vs RL", flat_returns, rl_returns), ("A&S+CVaR vs RL", as_cvar_returns, rl_returns)]:\n    t, p = newey_west_tstat(r1, r2)\n    sig = "***" if p < 0.01 else "**" if p < 0.05 else "*" if p < 0.1 else ""\n    print(f"{name}: t={t:.3f}, p={p:.4f} {sig}")'),
    new_markdown_cell('---'),
    new_markdown_cell('## 9. Save Results'),
    new_code_cell('perf_summary = {\n    "test_period": {"start": str(price_test.index.min().date()), "end": str(price_test.index.max().date()), "n_bars": len(price_test)},\n    "strategies": {\n        "flat_baseline": {k: float(v) for k, v in flat_metrics.items()},\n        "as_cvar": {k: float(v) for k, v in as_cvar_metrics.items()},\n        "rl_agent": {k: float(v) for k, v in rl_metrics.items()}\n    }\n}\nwith open(BACKTEST_DIR / "performance_summary.json", "w") as f:\n    json.dump(perf_summary, f, indent=2, default=str)\nlog.info(f"Saved: {BACKTEST_DIR / \'performance_summary.json\'}")\nprint("Backtest complete!")'),
]

with open('notebooks/05_backtest_analysis.ipynb', 'w') as f:
    nbformat.write(nb, f)
print('Notebook written successfully')
